// RTMLObservation.java
// $Header: /space/home/eng/cjm/cvs/org_estar_rtml/RTMLObservation.java,v 1.5 2005-05-04 18:56:52 cjm Exp $
package org.estar.rtml;

import java.io.*;
import java.net.*;
import java.util.*;

/**
 * This class is a data container for information contained in the observation nodes/tags of an RTML document.
 * @author Chris Mottram
 * @version $Revision: 1.5 $
 */
public class RTMLObservation implements Serializable, RTMLDeviceHolder
{
	/**
	 * Revision control system version id.
	 */
	public final static String RCSID = "$Id: RTMLObservation.java,v 1.5 2005-05-04 18:56:52 cjm Exp $";
	/**
	 * The device (instrument) of this observation.
	 * This can be null, in which case pick up the generic document device information.
	 */
	private RTMLDevice device = null;
	/**
	 * The target of this observation.
	 */
	private RTMLTarget target = null;
	/**
	 * The schedule of this observation.
	 */
	private RTMLSchedule schedule = null;
	/**
	 * A list of data generated by this observation.
	 * @see RTMLImageData
	 */
	private List imageDataList = null;

	/**
	 * Default constructor. Constructs an empty list for the returned image data.
	 * @see #imageDataList
	 */
	public RTMLObservation()
	{
		super();
		imageDataList = new Vector();
	}

	/**
	 * Set the device.
	 * @param device The device to set.
	 * @see #device
	 */
	public void setDevice(RTMLDevice d)
	{
		device = d;
	}

	/**
	 * Get the device.
	 * @return The device.
	 * @see #device
	 * @see RTMLDevice
	 */
	public RTMLDevice getDevice()
	{
		return device;
	}

	/**
	 * Set the observation target.
	 * @param t The target.
	 * @see #target
	 * @see RTMLTarget
	 */
	public void setTarget(RTMLTarget t)
	{
		target = t;
	}

	/**
	 * Get the observation target.
	 * @return The target.
	 * @see #target
	 * @see RTMLTarget
	 */
	public RTMLTarget getTarget()
	{
		return target;
	}

	/**
	 * Set the observation schedule.
	 * @param s The schedule.
	 * @see #schedule
	 * @see RTMLSchedule
	 */
	public void setSchedule(RTMLSchedule s)
	{
		schedule = s;
	}

	/**
	 * Get the observation schedule.
	 * @return The schedule.
	 * @see #schedule
	 * @see RTMLSchedule
	 */
	public RTMLSchedule getSchedule()
	{
		return schedule;
	}

	/**
	 * Add some image data to the list of image data.
	 * @param o The image data to add.
	 * @see #imageDataList
	 * @see RTMLImageData
	 */
	public void addImageData(RTMLImageData o)
	{
		imageDataList.add(o);
	}

	/**
	 * Set the image data at a particular index in the list
	 * @param i The index in the list.
	 * @param o The image data to set.
	 * @see #imageDataList
	 * @see RTMLImageData
	 */
	public void setImageData(int i,RTMLImageData o) throws Exception
	{
		imageDataList.set(i,o);
	}

	/**
	 * Get the image data at an index.
	 * @param i The index.
	 * @return The image data.
	 * @exception IndexOutOfBoundsException Thrown if the index is out of range.
	 */
	public RTMLImageData getImageData(int i) throws IndexOutOfBoundsException
	{
		return (RTMLImageData)(imageDataList.get(i));
	}

	/**
	 * Get the image data list.
	 * @return A list, full of instances of RTMLImageData.
	 */
	public List getImageDataList()
	{
		return imageDataList;
	}

	/**
	 * Get the number of elements in the image data list.
	 * @return A number of items in the list.
	 */
	public int getImageDataCount()
	{
		if(imageDataList != null)
			return imageDataList.size();
		else
			return 0;
	}

	/**
	 * Method to print out a string representation of this node.
	 */
	public String toString()
	{
		return toString("");
	}

	/**
	 * Method to print out a string representation of this node, with a prefix.
	 * @param prefix A string to prefix to each line of data we print out.
	 * @see #device
	 * @see #target
	 * @see #schedule
	 * @see #getImageData
	 * @see #getImageDataCount
	 */
	public String toString(String prefix)
	{
		RTMLImageData imageData = null;
		StringBuffer sb = null;
		
		sb = new StringBuffer();
		sb.append(prefix+"Observation\n");
		if(target != null)
			sb.append(prefix+target.toString("\t"));
		if(device != null)
			sb.append(prefix+device.toString("\t"));
		if(schedule != null)
			sb.append(prefix+schedule.toString("\t"));
		for(int i = 0; i < getImageDataCount(); i++)
		{
			imageData = getImageData(i);
			if(imageData != null)
				sb.append(prefix+imageData.toString("\t"));
		}
		return sb.toString();
	}
}
/*
** $Log: not supported by cvs2svn $
** Revision 1.4  2005/01/19 12:05:29  cjm
** Reorder toString prints.
**
** Revision 1.3  2005/01/19 11:53:28  cjm
** Added capability of having per-observation devices (instrument configs).
**
** Revision 1.2  2004/03/18 17:32:34  cjm
** Added imageDataType.
**
** Revision 1.1  2003/02/24 13:19:56  cjm
** Initial revision
**
*/
